stages:
  - test
  - deploy

services:
  - gitlab:dind

test:
  stage: test
  image: python:3.7

  before_script:
    - python --version
    - pip install -r requirements.txt

  script:
    - pytest

production:
  stage: deploy
  image: docker:latest

  before_script:
    - docker info
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

  script:
    - docker build -t inowas/processing:latest .
    - docker push inowas/processing

  only:
    - master
