version: "2.1"

services:
  app:
    image: inowas/processing:latest
    restart: always
    expose:
      - 5000
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.wiki.frontend.rule=Host: ${HOST_URL}"
      - "traefik.wiki.port=5000"
      - "traefik.wiki.protocol=http"
    networks:
      - web
      - default
    volumes:
      - .:/app
    environment:
      UPLOAD_FOLDER: '/uploads'

networks:
  web:
    external: true